services:
  inception-mariadb:
    container_name: inception-mariadb
    image: inception_mariadb:1.0
    restart: on-failure
    expose:
      - "3306"
    env_file:
      - .env
    build:
      context: ./requirements/mariadb/
      args:
        - DATABASE_NAME
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
        - DATABASE_ROOT_PASSWORD
      dockerfile: Dockerfile
    volumes:
      - inception-mariadb:/var/lib/mysql
    networks:
      - inception
  inception-nginx:
    container_name: inception-nginx
    image: inception_nginx:1.0
    restart: always
    volumes:
      - inception-nginx:/var/www/jbadaire.42.fr
    networks:
      - inception
    ports:
      - "443:443"
    expose:
      - "443"
    depends_on:
      - inception-mariadb
      - inception-wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
  inception-wordpress:
    container_name: inception-wordpress
    image: inception-wordpress:1.0
    restart: always
    depends_on:
      - inception-mariadb
    env_file:
      - .env
    volumes:
      - inception-nginx:/var/www/jbadaire.42.fr
    networks:
      - inception
    expose:
      - "9000"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile

volumes:
  inception-nginx:
    name: inception-nginx
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jbadaire/data/nginx
  inception-mariadb:
    name: inception-mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jbadaire/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge